# This file is managed by Qt Creator, do not edit!

set("CMAKE_BUILD_TYPE" "MinSizeRel" CACHE "STRING" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "C:/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake" CACHE "PATH" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "C:/Qt/6.2.3/android_x86/bin/qmake.bat" CACHE "STRING" "" FORCE)
set("CMAKE_PREFIX_PATH" "C:/Qt/6.2.3/android_x86" CACHE "STRING" "" FORCE)
set("CMAKE_C_COMPILER" "C:/Users/Yura/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_COMPILER" "C:/Users/Yura/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" CACHE "STRING" "" FORCE)
set("ANDROID_NATIVE_API_LEVEL" "23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "C:/Users/Yura/AppData/Local/Android/Sdk/ndk/21.3.6528147" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "C:/Users/Yura/AppData/Local/Android/Sdk/ndk/21.3.6528147/build/cmake/android.toolchain.cmake" CACHE "PATH" "" FORCE)
set("ANDROID_ABI" "x86" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "C:/Qt/6.2.3/android_x86" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "C:/Qt/6.2.3/mingw_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "C:/Users/Yura/AppData/Local/Android/Sdk" CACHE "PATH" "" FORCE)