import turtle
h=int(input('Введіть товщину лінії від 1 до 10'))
d=int(input('Введіть довжину лінії від 50 до =300'))
turtle.shape ('arrow')
turtle.width (h)
turtle.color('blue')
turtle.forward(d)
turtle.left(90)
turtle.color('yellow')
turtle.forward(d)
turtle.left(90)
turtle.color('red')
turtle.forward(d)
turtle.left(90)
turtle.color('green')
turtle.forward(d)
turtle.left(90)

turtle.exitonclick()